export const BASE_SET_PRODUCTS: 'BASE_SET_PRODUCTS' = 'BASE_SET_PRODUCTS';
export const BASE_GET_PRODUCTS: 'BASE_GET_PRODUCTS' = 'BASE_GET_PRODUCTS';
export const BASE_CREATE_PRODUCT: 'BASE_CREATE_PRODUCT' = 'BASE_CREATE_PRODUCT';
export const BASE_DELETE_PRODUCT: 'BASE_DELETE_PRODUCT' = 'BASE_DELETE_PRODUCT';


export const BASE_APP_LOADING: 'BASE_APP_LOADING' = 'BASE_APP_LOADING';