export const BASE_LOGIN_REQUEST: 'BASE_LOGIN_REQUEST' = 'BASE_LOGIN_REQUEST';
export const BASE_LOGIN_SUCCESS: 'BASE_LOGIN_SUCCESS' = 'BASE_LOGIN_SUCCESS';
export const BASE_LOGIN_ERROR: 'BASE_LOGIN_ERROR' = 'BASE_LOGIN_ERROR';
